// flow-typed signature: 884b1697a214f95b991dcd53542df34e
// flow-typed version: <<STUB>>/window_v^4.2.5/flow_v0.82.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'window'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'window' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'window/src/index' {
  declare module.exports: any;
}

declare module 'window/test/types' {
  declare module.exports: any;
}

declare module 'window/test/unit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'window/src/index.js' {
  declare module.exports: $Exports<'window/src/index'>;
}
declare module 'window/test/types.js' {
  declare module.exports: $Exports<'window/test/types'>;
}
declare module 'window/test/unit.js' {
  declare module.exports: $Exports<'window/test/unit'>;
}
